name: flutter_wallet
description: Flutter plugin to add pkpass to iOS wallet (Passbook)
version: 0.0.5
author: Vico Aguado <contacto@vico-aguado.com>
homepage: https://github.com/vico-aguado/flutter_wallet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterWalletPlugin
