name: greenpass_app
description: GreenPass App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+7

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  http: ^0.13.3
  intl: ^0.17.0
  country_codes: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  dart_base45: ^1.0.1
  dart_cose:
    git:
      url: https://github.com/jeroentrappers/dart_cose
  url_launcher: ^6.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  qr_mobile_vision: ^3.0.1
  app_settings: ^4.1.0
  modal_bottom_sheet: ^2.0.0
  flutter_vector_icons: ^1.0.0
  easy_localization: ^3.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  pretty_qr_code: ^2.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^4.2.0
  flag: ^5.0.0-nullsafety
  package_info: ^2.0.2
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.6
  flutter_markdown: ^0.6.2
  file_picker: ^3.0.3
  native_pdf_renderer: ^3.1.0
  crypto: ^3.0.1
  dio: ^4.0.0
  flutter_wallet:
    git:
      url: https://github.com/Hiyorimi/flutter_wallet
  ota_update: ^3.1.0
  pointycastle: ^3.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/tutorial/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
